framework:
    cache:
        default_redis_provider: '%env(DEFAULT_REDIS_PROVIDER)%'
        pools:
            ratelimiter.anonymous_api.cache:
                adapter: cache.adapter.redis
            ratelimiter.authenticated_api.cache:
                adapter: cache.adapter.redis
