framework:
    default_locale: nl
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
jms_translation:
    configs:
        app:
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src", "%kernel.project_dir%/public"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_dirs: [cache, data, logs, DataFixtures]
