controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"