parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    jms_translation.dumper.xlf_dumper:
        class: "%jms_translation.dumper.xliff_dumper.class%"
        calls:
            - [setSourceLanguage, ["%jms_translation.source_language%"]]
            - [setAddDate, [false]]
