<?php

namespace App\DataFixtures;

use App\Entity\Portfolio\Block;
use App\Entity\Portfolio\HousingStock;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
use RuntimeException;
use Symfony\Component\Validator\ConstraintViolation;
use Symfony\Component\Validator\Validation;

class LoadBlockData extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $objectManager): void
    {
        $blocks = [
            ['code' => 'ALG1002', 'name' => 'Algemeen 1002', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1003', 'name' => 'Algemeen 1003', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1006', 'name' => 'Algemeen 1006', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1007', 'name' => 'Algemeen 1007', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1009', 'name' => 'Algemeen 1009', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1010', 'name' => 'Algemeen 1010', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1011', 'name' => 'Algemeen 1011', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1012', 'name' => 'Algemeen 1012', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1013', 'name' => 'Algemeen 1013', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1014', 'name' => 'Algemeen 1014', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1016', 'name' => 'Algemeen 1016', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1017', 'name' => 'Algemeen 1017', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1018', 'name' => 'Algemeen 1018', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1019', 'name' => 'Algemeen 1019', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1020', 'name' => 'Algemeen 1020', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1021', 'name' => 'Algemeen 1021', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1022', 'name' => 'Algemeen 1022', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1023', 'name' => 'Algemeen 1023', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1024', 'name' => 'Algemeen 1024', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1025', 'name' => 'Algemeen 1025', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1027', 'name' => 'Algemeen 1027', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1028', 'name' => 'Algemeen 1028', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1029', 'name' => 'Algemeen 1029', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1030', 'name' => 'Algemeen 1030', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1031', 'name' => 'Algemeen 1031', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1032', 'name' => 'Algemeen 1032', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1033', 'name' => 'Algemeen 1033', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1034', 'name' => 'Algemeen 1034', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1035', 'name' => 'Algemeen 1035', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1036', 'name' => 'Algemeen 1036', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1037', 'name' => 'Algemeen 1037', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1039', 'name' => 'Algemeen 1039', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1040', 'name' => 'Algemeen 1040', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1041', 'name' => 'Algemeen 1041', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1042', 'name' => 'Algemeen 1042', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1045', 'name' => 'Algemeen 1045', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1046', 'name' => 'Algemeen 1046', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1047', 'name' => 'Algemeen 1047', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1048', 'name' => 'Algemeen 1048', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1049', 'name' => 'Algemeen 1049', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1051', 'name' => 'Algemeen 1051', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1052', 'name' => 'Algemeen 1052', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1053', 'name' => 'Algemeen 1053', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1054', 'name' => 'Algemeen 1054', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1056', 'name' => 'Algemeen 1056', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1058', 'name' => 'Algemeen 1058', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1059', 'name' => 'Algemeen 1059', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1061', 'name' => 'Algemeen 1061', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1063', 'name' => 'Algemeen 1063', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1064', 'name' => 'Algemeen 1064', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1066', 'name' => 'Algemeen 1066', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1067', 'name' => 'Algemeen 1067', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1068', 'name' => 'Algemeen 1068', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1069', 'name' => 'Algemeen 1069', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1070', 'name' => 'Algemeen 1070', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1071', 'name' => 'Algemeen 1071', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1072', 'name' => 'Algemeen 1072', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1073', 'name' => 'Algemeen 1073', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1074', 'name' => 'Algemeen 1074', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1075', 'name' => 'Algemeen 1075', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1076', 'name' => 'Algemeen 1076', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1077', 'name' => 'Algemeen 1077', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1078', 'name' => 'Algemeen 1078', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1079', 'name' => 'Algemeen 1079', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1080', 'name' => 'Algemeen 1080', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1082', 'name' => 'Algemeen 1082', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1085', 'name' => 'Algemeen 1085', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1086', 'name' => 'Algemeen 1086', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1087', 'name' => 'Algemeen 1087', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1088', 'name' => 'Algemeen 1088', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1089', 'name' => 'Algemeen 1089', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1090', 'name' => 'Algemeen 1090', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1091', 'name' => 'Algemeen 1091', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1093', 'name' => 'Algemeen 1093', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1094', 'name' => 'Algemeen 1094', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1095', 'name' => 'Algemeen 1095', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1101', 'name' => 'Algemeen 1101', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1102', 'name' => 'Algemeen 1102', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1104', 'name' => 'Algemeen 1104', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1106', 'name' => 'Algemeen 1106', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1107', 'name' => 'Algemeen 1107', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1109', 'name' => 'Algemeen 1109', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1110', 'name' => 'Algemeen 1110', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1111', 'name' => 'Algemeen 1111', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1112', 'name' => 'Algemeen 1112', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1113', 'name' => 'Algemeen 1113', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1114', 'name' => 'Algemeen 1114', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1116', 'name' => 'Algemeen 1116', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1117', 'name' => 'Algemeen 1117', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1118', 'name' => 'Algemeen 1118', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1120', 'name' => 'Algemeen 1120', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1131', 'name' => 'Algemeen 1131', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1132', 'name' => 'Algemeen 1132', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1135', 'name' => 'Algemeen 1135', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1136', 'name' => 'Algemeen 1136', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1138', 'name' => 'Algemeen 1138', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1139', 'name' => 'Algemeen 1139', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1140', 'name' => 'Algemeen 1140', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1143', 'name' => 'Algemeen 1143', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1144', 'name' => 'Algemeen 1144', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1145', 'name' => 'Algemeen 1145', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1146', 'name' => 'Algemeen 1146', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1151', 'name' => 'Algemeen 1151', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1152', 'name' => 'Algemeen 1152', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1153', 'name' => 'Algemeen 1153', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1154', 'name' => 'Algemeen 1154', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1156', 'name' => 'Algemeen 1156', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1157', 'name' => 'Algemeen 1157', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1158', 'name' => 'Algemeen 1158', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1160', 'name' => 'Algemeen 1160', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1201', 'name' => 'Algemeen 1201', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1202', 'name' => 'Algemeen 1202', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1203', 'name' => 'Algemeen 1203', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1205', 'name' => 'Algemeen 1205', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1206', 'name' => 'Algemeen 1206', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1207', 'name' => 'Algemeen 1207', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1210', 'name' => 'Algemeen 1210', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1211', 'name' => 'Algemeen 1211', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1212', 'name' => 'Algemeen 1212', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1214', 'name' => 'Algemeen 1214', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1215', 'name' => 'Algemeen 1215', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1217', 'name' => 'Algemeen 1217', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1219', 'name' => 'Algemeen 1219', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1220', 'name' => 'Algemeen 1220', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1221', 'name' => 'Algemeen 1221', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1222', 'name' => 'Algemeen 1222', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1225', 'name' => 'Algemeen 1225', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1226', 'name' => 'Algemeen 1226', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1227', 'name' => 'Algemeen 1227', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1236', 'name' => 'Algemeen 1236', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1237', 'name' => 'Algemeen 1237', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1251', 'name' => 'Algemeen 1251', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1253', 'name' => 'Algemeen 1253', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1254', 'name' => 'Algemeen 1254', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1255', 'name' => 'Algemeen 1255', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1260', 'name' => 'Algemeen 1260', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1261', 'name' => 'Algemeen 1261', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1262', 'name' => 'Algemeen 1262', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1301', 'name' => 'Algemeen 1301', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1303', 'name' => 'Algemeen 1303', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1304', 'name' => 'Algemeen 1304', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1320', 'name' => 'Algemeen 1320', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1321', 'name' => 'Algemeen 1321', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1326', 'name' => 'Algemeen 1326', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1327', 'name' => 'Algemeen 1327', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1329', 'name' => 'Algemeen 1329', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1330', 'name' => 'Algemeen 1330', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1332', 'name' => 'Algemeen 1332', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1333', 'name' => 'Algemeen 1333', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1334', 'name' => 'Algemeen 1334', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1335', 'name' => 'Algemeen 1335', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1349', 'name' => 'Algemeen 1349', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1350', 'name' => 'Algemeen 1350', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1352', 'name' => 'Algemeen 1352', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1353', 'name' => 'Algemeen 1353', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1391', 'name' => 'Algemeen 1391', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1401', 'name' => 'Algemeen 1401', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1402', 'name' => 'Algemeen 1402', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1407', 'name' => 'Algemeen 1407', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1408', 'name' => 'Algemeen 1408', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1409', 'name' => 'Algemeen 1409', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1410', 'name' => 'Algemeen 1410', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1411', 'name' => 'Algemeen 1411', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1412', 'name' => 'Algemeen 1412', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1413', 'name' => 'Algemeen 1413', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1414', 'name' => 'Algemeen 1414', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1415', 'name' => 'Algemeen 1415', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1416', 'name' => 'Algemeen 1416', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1417', 'name' => 'Algemeen 1417', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1418', 'name' => 'Algemeen 1418', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1419', 'name' => 'Algemeen 1419', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1420', 'name' => 'Algemeen 1420', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1421', 'name' => 'Algemeen 1421', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1422', 'name' => 'Algemeen 1422', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1423', 'name' => 'Algemeen 1423', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1426', 'name' => 'Algemeen 1426', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1428', 'name' => 'Algemeen 1428', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1429', 'name' => 'Algemeen 1429', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1430', 'name' => 'Algemeen 1430', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1431', 'name' => 'Algemeen 1431', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1432', 'name' => 'Algemeen 1432', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1433', 'name' => 'Algemeen 1433', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1435', 'name' => 'Algemeen 1435', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1436', 'name' => 'Algemeen 1436', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1437', 'name' => 'Algemeen 1437', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1451', 'name' => 'Algemeen 1451', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1500', 'name' => 'Algemeen 1500', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1501', 'name' => 'Algemeen 1501', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1502', 'name' => 'Algemeen 1502', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1504', 'name' => 'Algemeen 1504', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1517', 'name' => 'Algemeen 1517', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1523', 'name' => 'Algemeen 1523', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1524', 'name' => 'Algemeen 1524', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1525', 'name' => 'Algemeen 1525', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1526', 'name' => 'Algemeen 1526', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1527', 'name' => 'Algemeen 1527', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1528', 'name' => 'Algemeen 1528', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1529', 'name' => 'Algemeen 1529', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1530', 'name' => 'Algemeen 1530', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1531', 'name' => 'Algemeen 1531', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1532', 'name' => 'Algemeen 1532', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1533', 'name' => 'Algemeen 1533', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1534', 'name' => 'Algemeen 1534', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1536', 'name' => 'Algemeen 1536', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1537', 'name' => 'Algemeen 1537', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1538', 'name' => 'Algemeen 1538', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1540', 'name' => 'Algemeen 1540', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1541', 'name' => 'Algemeen 1541', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1542', 'name' => 'Algemeen 1542', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1544', 'name' => 'Algemeen 1544', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1545', 'name' => 'Algemeen 1545', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1546', 'name' => 'Algemeen 1546', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1547', 'name' => 'Algemeen 1547', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1548', 'name' => 'Algemeen 1548', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1549', 'name' => 'Algemeen 1549', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1550', 'name' => 'Algemeen 1550', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1551', 'name' => 'Algemeen 1551', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1552', 'name' => 'Algemeen 1552', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1553', 'name' => 'Algemeen 1553', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1555', 'name' => 'Algemeen 1555', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1557', 'name' => 'Algemeen 1557', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1558', 'name' => 'Algemeen 1558', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1560', 'name' => 'Algemeen 1560', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1561', 'name' => 'Algemeen 1561', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1562', 'name' => 'Algemeen 1562', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1563', 'name' => 'Algemeen 1563', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1564', 'name' => 'Algemeen 1564', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1565', 'name' => 'Algemeen 1565', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1570', 'name' => 'Algemeen 1570', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1571', 'name' => 'Algemeen 1571', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1573', 'name' => 'Algemeen 1573', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1574', 'name' => 'Algemeen 1574', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1575', 'name' => 'Algemeen 1575', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1576', 'name' => 'Algemeen 1576', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1577', 'name' => 'Algemeen 1577', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1578', 'name' => 'Algemeen 1578', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1579', 'name' => 'Algemeen 1579', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1580', 'name' => 'Algemeen 1580', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1581', 'name' => 'Algemeen 1581', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1584', 'name' => 'Algemeen 1584', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1585', 'name' => 'Algemeen 1585', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1587', 'name' => 'Algemeen 1587', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1588', 'name' => 'Algemeen 1588', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1589', 'name' => 'Algemeen 1589', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1590', 'name' => 'Algemeen 1590', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1591', 'name' => 'Algemeen 1591', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1592', 'name' => 'Algemeen 1592', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1593', 'name' => 'Algemeen 1593', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG1594', 'name' => 'Algemeen 1594', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2804', 'name' => 'Algemeen 2804', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2812', 'name' => 'Algemeen 2812', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2813', 'name' => 'Algemeen 2813', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2815', 'name' => 'Algemeen 2815', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2821', 'name' => 'Algemeen 2821', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2822', 'name' => 'Algemeen 2822', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2824', 'name' => 'Algemeen 2824', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2825', 'name' => 'Algemeen 2825', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2826', 'name' => 'Algemeen 2826', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2827', 'name' => 'Algemeen 2827', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2828', 'name' => 'Algemeen 2828', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2833', 'name' => 'Algemeen 2833', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2836', 'name' => 'Algemeen 2836', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2837', 'name' => 'Algemeen 2837', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2840', 'name' => 'Algemeen 2840', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2841', 'name' => 'Algemeen 2841', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2842', 'name' => 'Algemeen 2842', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2844', 'name' => 'Algemeen 2844', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2846', 'name' => 'Algemeen 2846', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2847', 'name' => 'Algemeen 2847', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2849', 'name' => 'Algemeen 2849', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2850', 'name' => 'Algemeen 2850', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2851', 'name' => 'Algemeen 2851', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2853', 'name' => 'Algemeen 2853', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2863', 'name' => 'Algemeen 2863', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2865', 'name' => 'Algemeen 2865', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2870', 'name' => 'Algemeen 2870', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2871', 'name' => 'Algemeen 2871', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2872', 'name' => 'Algemeen 2872', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2874', 'name' => 'Algemeen 2874', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2876', 'name' => 'Algemeen 2876', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2877', 'name' => 'Algemeen 2877', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2878', 'name' => 'Algemeen 2878', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2879', 'name' => 'Algemeen 2879', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2880', 'name' => 'Algemeen 2880', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2881', 'name' => 'Algemeen 2881', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2882', 'name' => 'Algemeen 2882', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2883', 'name' => 'Algemeen 2883', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2884', 'name' => 'Algemeen 2884', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2886', 'name' => 'Algemeen 2886', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2887', 'name' => 'Algemeen 2887', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2888', 'name' => 'Algemeen 2888', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2896', 'name' => 'Algemeen 2896', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2897', 'name' => 'Algemeen 2897', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2906', 'name' => 'Algemeen 2906', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2908', 'name' => 'Algemeen 2908', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2911', 'name' => 'Algemeen 2911', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2913', 'name' => 'Algemeen 2913', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2914', 'name' => 'Algemeen 2914', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2918', 'name' => 'Algemeen 2918', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2919', 'name' => 'Algemeen 2919', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2922', 'name' => 'Algemeen 2922', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2923', 'name' => 'Algemeen 2923', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2931', 'name' => 'Algemeen 2931', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2932', 'name' => 'Algemeen 2932', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2934', 'name' => 'Algemeen 2934', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2935', 'name' => 'Algemeen 2935', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2937', 'name' => 'Algemeen 2937', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2938', 'name' => 'Algemeen 2938', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2947', 'name' => 'Algemeen 2947', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2963', 'name' => 'Algemeen 2963', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2964', 'name' => 'Algemeen 2964', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2965', 'name' => 'Algemeen 2965', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2966', 'name' => 'Algemeen 2966', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2969', 'name' => 'Algemeen 2969', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2970', 'name' => 'Algemeen 2970', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG2971', 'name' => 'Algemeen 2971', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3602', 'name' => 'Algemeen 3602', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3605', 'name' => 'Algemeen 3605', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3608', 'name' => 'Algemeen 3608', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3609', 'name' => 'Algemeen 3609', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3610', 'name' => 'Algemeen 3610', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3611', 'name' => 'Algemeen 3611', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3612', 'name' => 'Algemeen 3612', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3613', 'name' => 'Algemeen 3613', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3614', 'name' => 'Algemeen 3614', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3615', 'name' => 'Algemeen 3615', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3616', 'name' => 'Algemeen 3616', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3617', 'name' => 'Algemeen 3617', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3618', 'name' => 'Algemeen 3618', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3619', 'name' => 'Algemeen 3619', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3620', 'name' => 'Algemeen 3620', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3621', 'name' => 'Algemeen 3621', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3622', 'name' => 'Algemeen 3622', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3623', 'name' => 'Algemeen 3623', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3625', 'name' => 'Algemeen 3625', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3626', 'name' => 'Algemeen 3626', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3627', 'name' => 'Algemeen 3627', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3628', 'name' => 'Algemeen 3628', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3630', 'name' => 'Algemeen 3630', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3631', 'name' => 'Algemeen 3631', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3633', 'name' => 'Algemeen 3633', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3634', 'name' => 'Algemeen 3634', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3635', 'name' => 'Algemeen 3635', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3636', 'name' => 'Algemeen 3636', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3637', 'name' => 'Algemeen 3637', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3638', 'name' => 'Algemeen 3638', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3640', 'name' => 'Algemeen 3640', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3641', 'name' => 'Algemeen 3641', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3652', 'name' => 'Algemeen 3652', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3660', 'name' => 'Algemeen 3660', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3661', 'name' => 'Algemeen 3661', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3664', 'name' => 'Algemeen 3664', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3665', 'name' => 'Algemeen 3665', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3667', 'name' => 'Algemeen 3667', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3668', 'name' => 'Algemeen 3668', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3670', 'name' => 'Algemeen 3670', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3671', 'name' => 'Algemeen 3671', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3672', 'name' => 'Algemeen 3672', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3675', 'name' => 'Algemeen 3675', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3677', 'name' => 'Algemeen 3677', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3684', 'name' => 'Algemeen 3684', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3686', 'name' => 'Algemeen 3686', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3688', 'name' => 'Algemeen 3688', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3705', 'name' => 'Algemeen 3705', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3706', 'name' => 'Algemeen 3706', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3707', 'name' => 'Algemeen 3707', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3708', 'name' => 'Algemeen 3708', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3709', 'name' => 'Algemeen 3709', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3710', 'name' => 'Algemeen 3710', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3713', 'name' => 'Algemeen 3713', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3719', 'name' => 'Algemeen 3719', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3725', 'name' => 'Algemeen 3725', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3728', 'name' => 'Algemeen 3728', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3736', 'name' => 'Algemeen 3736', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3741', 'name' => 'Algemeen 3741', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3742', 'name' => 'Algemeen 3742', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3745', 'name' => 'Algemeen 3745', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3750', 'name' => 'Algemeen 3750', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3752', 'name' => 'Algemeen 3752', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3756', 'name' => 'Algemeen 3756', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3757', 'name' => 'Algemeen 3757', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3759', 'name' => 'Algemeen 3759', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3760', 'name' => 'Algemeen 3760', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3761', 'name' => 'Algemeen 3761', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3762', 'name' => 'Algemeen 3762', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3763', 'name' => 'Algemeen 3763', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3764', 'name' => 'Algemeen 3764', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3765', 'name' => 'Algemeen 3765', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3766', 'name' => 'Algemeen 3766', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3767', 'name' => 'Algemeen 3767', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3768', 'name' => 'Algemeen 3768', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3769', 'name' => 'Algemeen 3769', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3786', 'name' => 'Algemeen 3786', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3787', 'name' => 'Algemeen 3787', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3802', 'name' => 'Algemeen 3802', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3803', 'name' => 'Algemeen 3803', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3804', 'name' => 'Algemeen 3804', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3805', 'name' => 'Algemeen 3805', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3810', 'name' => 'Algemeen 3810', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3811', 'name' => 'Algemeen 3811', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3812', 'name' => 'Algemeen 3812', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3813', 'name' => 'Algemeen 3813', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3814', 'name' => 'Algemeen 3814', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3815', 'name' => 'Algemeen 3815', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3816', 'name' => 'Algemeen 3816', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3818', 'name' => 'Algemeen 3818', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3819', 'name' => 'Algemeen 3819', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3820', 'name' => 'Algemeen 3820', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3821', 'name' => 'Algemeen 3821', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3822', 'name' => 'Algemeen 3822', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3830', 'name' => 'Algemeen 3830', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3831', 'name' => 'Algemeen 3831', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3832', 'name' => 'Algemeen 3832', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3833', 'name' => 'Algemeen 3833', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3835', 'name' => 'Algemeen 3835', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3836', 'name' => 'Algemeen 3836', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG3837', 'name' => 'Algemeen 3837', 'housingstock' => 'DobroTest01'],
            ['code' => 'ALG9001', 'name' => 'Algemeen 9001', 'housingstock' => 'DobroTest01'],
        ];

        foreach ($blocks as $block) {
            $blockObject = new Block();

            if (empty($block['code'])) {
                throw new RuntimeException("code may not be empty, it's used as a variable reference in the data fixtures.");
            } else {
                $blockObject->setCode($block['code']);
            }

            if (isset($block['name']) && ($block['name'] !== '' && $block['name'] !== '0')) {
                $blockObject->setName($block['name']);
            }

            if (!empty($block['financialNumber'])) {
                $blockObject->setFinancialNumber($block['financialNumber']);
            }

            if (isset($block['description']) && ($block['description'] !== '' && $block['description'] !== '0')) {
                $blockObject->setDescription($block['description']);
            }

            if (isset($block['housingstock']) && ($block['housingstock'] !== '' && $block['housingstock'] !== '0')) {
                /** @var HousingStock $housingStock */
                $housingStock = $this->getReference('housingstock_' . $block['housingstock'], HousingStock::class);
                $blockObject->setHousingStock($housingStock);
            }

            $blockObject->setCreationTime();
            $blockObject->setLastChangeTime();

            $validator = Validation::createValidator();
            $errors = $validator->validate($blockObject);
            if (count($errors) > 0) {
                $messages = [];
                foreach ($errors as $error) {
                    /** @var ConstraintViolation $error */
                    $messages[] = $error->getMessage();
                }

                throw new RuntimeException(implode(', ', $messages));
            }

            $objectManager->persist($blockObject);
            $this->addReference('block_' . $block['code'], $blockObject);
        }

        $objectManager->flush();
    }

    public function getDependencies(): array
    {
        return [
            LoadHousingStocksData::class,
        ];
    }
}