<?php

namespace App\DataFixtures;

use App\Entity\Portfolio\Municipality;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use RuntimeException;
use Symfony\Component\Validator\ConstraintViolation;
use Symfony\Component\Validator\Validation;

class LoadMunicipalityData extends Fixture
{
    public function load(ObjectManager $objectManager): void
    {
        $municipalities = [
            ['code' => '14', 'name' => "Groningen"],
            ['code' => '34', 'name' => "Almere"],
            ['code' => '37', 'name' => "Stadskanaal"],
            ['code' => '47', 'name' => "Veendam"],
            ['code' => '50', 'name' => "Zeewolde"],
            ['code' => '59', 'name' => "Achtkarspelen"],
            ['code' => '60', 'name' => "Ameland"],
            ['code' => '72', 'name' => "Harlingen"],
            ['code' => '74', 'name' => "Heerenveen"],
            ['code' => '80', 'name' => "Leeuwarden"],
            ['code' => '85', 'name' => "Ooststellingwerf"],
            ['code' => '86', 'name' => "Opsterland"],
            ['code' => '88', 'name' => "Schiermonnikoog"],
            ['code' => '90', 'name' => "Smallingerland"],
            ['code' => '93', 'name' => "Terschelling"],
            ['code' => '96', 'name' => "Vlieland"],
            ['code' => '98', 'name' => "Weststellingwerf"],
            ['code' => '106', 'name' => "Assen"],
            ['code' => '109', 'name' => "Coevorden"],
            ['code' => '114', 'name' => "Emmen"],
            ['code' => '118', 'name' => "Hoogeveen"],
            ['code' => '119', 'name' => "Meppel"],
            ['code' => '141', 'name' => "Almelo"],
            ['code' => '147', 'name' => "Borne"],
            ['code' => '148', 'name' => "Dalfsen"],
            ['code' => '150', 'name' => "Deventer"],
            ['code' => '153', 'name' => "Enschede"],
            ['code' => '158', 'name' => "Haaksbergen"],
            ['code' => '160', 'name' => "Hardenberg"],
            ['code' => '163', 'name' => "Hellendoorn"],
            ['code' => '164', 'name' => "Hengelo"],
            ['code' => '166', 'name' => "Kampen"],
            ['code' => '168', 'name' => "Losser"],
            ['code' => '171', 'name' => "Noordoostpolder"],
            ['code' => '173', 'name' => "Oldenzaal"],
            ['code' => '175', 'name' => "Ommen"],
            ['code' => '177', 'name' => "Raalte"],
            ['code' => '180', 'name' => "Staphorst"],
            ['code' => '183', 'name' => "Tubbergen"],
            ['code' => '184', 'name' => "Urk"],
            ['code' => '189', 'name' => "Wierden"],
            ['code' => '193', 'name' => "Zwolle"],
            ['code' => '197', 'name' => "Aalten"],
            ['code' => '200', 'name' => "Apeldoorn"],
            ['code' => '202', 'name' => "Arnhem"],
            ['code' => '203', 'name' => "Barneveld"],
            ['code' => '209', 'name' => "Beuningen"],
            ['code' => '213', 'name' => "Brummen"],
            ['code' => '214', 'name' => "Buren"],
            ['code' => '216', 'name' => "Culemborg"],
            ['code' => '221', 'name' => "Doesburg"],
            ['code' => '222', 'name' => "Doetinchem"],
            ['code' => '225', 'name' => "Druten"],
            ['code' => '226', 'name' => "Duiven"],
            ['code' => '228', 'name' => "Ede"],
            ['code' => '230', 'name' => "Elburg"],
            ['code' => '232', 'name' => "Epe"],
            ['code' => '233', 'name' => "Ermelo"],
            ['code' => '243', 'name' => "Harderwijk"],
            ['code' => '244', 'name' => "Hattem"],
            ['code' => '246', 'name' => "Heerde"],
            ['code' => '252', 'name' => "Heumen"],
            ['code' => '262', 'name' => "Lochem"],
            ['code' => '263', 'name' => "Maasdriel"],
            ['code' => '267', 'name' => "Nijkerk"],
            ['code' => '268', 'name' => "Nijmegen"],
            ['code' => '269', 'name' => "Oldebroek"],
            ['code' => '273', 'name' => "Putten"],
            ['code' => '274', 'name' => "Renkum"],
            ['code' => '275', 'name' => "Rheden"],
            ['code' => '277', 'name' => "Rozendaal"],
            ['code' => '279', 'name' => "Scherpenzeel"],
            ['code' => '281', 'name' => "Tiel"],
            ['code' => '285', 'name' => "Voorst"],
            ['code' => '289', 'name' => "Wageningen"],
            ['code' => '293', 'name' => "Westervoort"],
            ['code' => '294', 'name' => "Winterswijk"],
            ['code' => '296', 'name' => "Wijchen"],
            ['code' => '297', 'name' => "Zaltbommel"],
            ['code' => '299', 'name' => "Zevenaar"],
            ['code' => '301', 'name' => "Zutphen"],
            ['code' => '302', 'name' => "Nunspeet"],
            ['code' => '303', 'name' => "Dronten"],
            ['code' => '307', 'name' => "Amersfoort"],
            ['code' => '308', 'name' => "Baarn"],
            ['code' => '310', 'name' => "De Bilt"],
            ['code' => '312', 'name' => "Bunnik"],
            ['code' => '313', 'name' => "Bunschoten"],
            ['code' => '317', 'name' => "Eemnes"],
            ['code' => '321', 'name' => "Houten"],
            ['code' => '327', 'name' => "Leusden"],
            ['code' => '331', 'name' => "Lopik"],
            ['code' => '335', 'name' => "Montfoort"],
            ['code' => '339', 'name' => "Renswoude"],
            ['code' => '340', 'name' => "Rhenen"],
            ['code' => '342', 'name' => "Soest"],
            ['code' => '344', 'name' => "Utrecht"],
            ['code' => '345', 'name' => "Veenendaal"],
            ['code' => '351', 'name' => "Woudenberg"],
            ['code' => '352', 'name' => "Wijk bij Duurstede"],
            ['code' => '353', 'name' => "IJsselstein"],
            ['code' => '355', 'name' => "Zeist"],
            ['code' => '356', 'name' => "Nieuwegein"],
            ['code' => '358', 'name' => "Aalsmeer"],
            ['code' => '361', 'name' => "Alkmaar"],
            ['code' => '362', 'name' => "Amstelveen"],
            ['code' => '363', 'name' => "Amsterdam"],
            ['code' => '370', 'name' => "Beemster"],
            ['code' => '373', 'name' => "Bergen (NH.)"],
            ['code' => '375', 'name' => "Beverwijk"],
            ['code' => '376', 'name' => "Blaricum"],
            ['code' => '377', 'name' => "Bloemendaal"],
            ['code' => '383', 'name' => "Castricum"],
            ['code' => '384', 'name' => "Diemen"],
            ['code' => '385', 'name' => "Edam-Volendam"],
            ['code' => '388', 'name' => "Enkhuizen"],
            ['code' => '392', 'name' => "Haarlem"],
            ['code' => '394', 'name' => "Haarlemmermeer"],
            ['code' => '396', 'name' => "Heemskerk"],
            ['code' => '397', 'name' => "Heemstede"],
            ['code' => '398', 'name' => "Heerhugowaard"],
            ['code' => '399', 'name' => "Heiloo"],
            ['code' => '400', 'name' => "Den Helder"],
            ['code' => '402', 'name' => "Hilversum"],
            ['code' => '405', 'name' => "Hoorn"],
            ['code' => '406', 'name' => "Huizen"],
            ['code' => '415', 'name' => "Landsmeer"],
            ['code' => '416', 'name' => "Langedijk"],
            ['code' => '417', 'name' => "Laren"],
            ['code' => '420', 'name' => "Medemblik"],
            ['code' => '431', 'name' => "Oostzaan"],
            ['code' => '432', 'name' => "Opmeer"],
            ['code' => '437', 'name' => "Ouder-Amstel"],
            ['code' => '439', 'name' => "Purmerend"],
            ['code' => '441', 'name' => "Schagen"],
            ['code' => '448', 'name' => "Texel"],
            ['code' => '450', 'name' => "Uitgeest"],
            ['code' => '451', 'name' => "Uithoorn"],
            ['code' => '453', 'name' => "Velsen"],
            ['code' => '457', 'name' => "Weesp"],
            ['code' => '473', 'name' => "Zandvoort"],
            ['code' => '479', 'name' => "Zaanstad"],
            ['code' => '482', 'name' => "Alblasserdam"],
            ['code' => '484', 'name' => "Alphen aan den Rijn"],
            ['code' => '489', 'name' => "Barendrecht"],
            ['code' => '498', 'name' => "Drechterland"],
            ['code' => '501', 'name' => "Brielle"],
            ['code' => '502', 'name' => "Capelle aan den IJssel"],
            ['code' => '503', 'name' => "Delft"],
            ['code' => '505', 'name' => "Dordrecht"],
            ['code' => '512', 'name' => "Gorinchem"],
            ['code' => '513', 'name' => "Gouda"],
            ['code' => '518', 'name' => "'s-Gravenhage"],
            ['code' => '523', 'name' => "Hardinxveld-Giessendam"],
            ['code' => '530', 'name' => "Hellevoetsluis"],
            ['code' => '531', 'name' => "Hendrik-Ido-Ambacht"],
            ['code' => '532', 'name' => "Stede Broec"],
            ['code' => '534', 'name' => "Hillegom"],
            ['code' => '537', 'name' => "Katwijk"],
            ['code' => '542', 'name' => "Krimpen aan den IJssel"],
            ['code' => '546', 'name' => "Leiden"],
            ['code' => '547', 'name' => "Leiderdorp"],
            ['code' => '553', 'name' => "Lisse"],
            ['code' => '556', 'name' => "Maassluis"],
            ['code' => '569', 'name' => "Nieuwkoop"],
            ['code' => '575', 'name' => "Noordwijk"],
            ['code' => '579', 'name' => "Oegstgeest"],
            ['code' => '589', 'name' => "Oudewater"],
            ['code' => '590', 'name' => "Papendrecht"],
            ['code' => '597', 'name' => "Ridderkerk"],
            ['code' => '599', 'name' => "Rotterdam"],
            ['code' => '603', 'name' => "Rijswijk"],
            ['code' => '606', 'name' => "Schiedam"],
            ['code' => '610', 'name' => "Sliedrecht"],
            ['code' => '613', 'name' => "Albrandswaard"],
            ['code' => '614', 'name' => "Westvoorne"],
            ['code' => '622', 'name' => "Vlaardingen"],
            ['code' => '626', 'name' => "Voorschoten"],
            ['code' => '627', 'name' => "Waddinxveen"],
            ['code' => '629', 'name' => "Wassenaar"],
            ['code' => '632', 'name' => "Woerden"],
            ['code' => '637', 'name' => "Zoetermeer"],
            ['code' => '638', 'name' => "Zoeterwoude"],
            ['code' => '642', 'name' => "Zwijndrecht"],
            ['code' => '654', 'name' => "Borsele"],
            ['code' => '664', 'name' => "Goes"],
            ['code' => '668', 'name' => "West Maas en Waal"],
            ['code' => '677', 'name' => "Hulst"],
            ['code' => '678', 'name' => "Kapelle"],
            ['code' => '687', 'name' => "Middelburg"],
            ['code' => '703', 'name' => "Reimerswaal"],
            ['code' => '715', 'name' => "Terneuzen"],
            ['code' => '716', 'name' => "Tholen"],
            ['code' => '717', 'name' => "Veere"],
            ['code' => '718', 'name' => "Vlissingen"],
            ['code' => '736', 'name' => "De Ronde Venen"],
            ['code' => '737', 'name' => "Tytsjerksteradiel"],
            ['code' => '743', 'name' => "Asten"],
            ['code' => '744', 'name' => "Baarle-Nassau"],
            ['code' => '748', 'name' => "Bergen op Zoom"],
            ['code' => '753', 'name' => "Best"],
            ['code' => '755', 'name' => "Boekel"],
            ['code' => '756', 'name' => "Boxmeer"],
            ['code' => '757', 'name' => "Boxtel"],
            ['code' => '758', 'name' => "Breda"],
            ['code' => '762', 'name' => "Deurne"],
            ['code' => '765', 'name' => "Pekela"],
            ['code' => '766', 'name' => "Dongen"],
            ['code' => '770', 'name' => "Eersel"],
            ['code' => '772', 'name' => "Eindhoven"],
            ['code' => '777', 'name' => "Etten-Leur"],
            ['code' => '779', 'name' => "Geertruidenberg"],
            ['code' => '784', 'name' => "Gilze en Rijen"],
            ['code' => '785', 'name' => "Goirle"],
            ['code' => '786', 'name' => "Grave"],
            ['code' => '794', 'name' => "Helmond"],
            ['code' => '796', 'name' => "'s-Hertogenbosch"],
            ['code' => '797', 'name' => "Heusden"],
            ['code' => '798', 'name' => "Hilvarenbeek"],
            ['code' => '809', 'name' => "Loon op Zand"],
            ['code' => '815', 'name' => "Mill en Sint Hubert"],
            ['code' => '820', 'name' => "Nuenen, Gerwen en Nederwetten"],
            ['code' => '823', 'name' => "Oirschot"],
            ['code' => '824', 'name' => "Oisterwijk"],
            ['code' => '826', 'name' => "Oosterhout"],
            ['code' => '828', 'name' => "Oss"],
            ['code' => '840', 'name' => "Rucphen"],
            ['code' => '845', 'name' => "Sint-Michielsgestel"],
            ['code' => '847', 'name' => "Someren"],
            ['code' => '848', 'name' => "Son en Breugel"],
            ['code' => '851', 'name' => "Steenbergen"],
            ['code' => '852', 'name' => "Waterland"],
            ['code' => '855', 'name' => "Tilburg"],
            ['code' => '856', 'name' => "Uden"],
            ['code' => '858', 'name' => "Valkenswaard"],
            ['code' => '861', 'name' => "Veldhoven"],
            ['code' => '865', 'name' => "Vught"],
            ['code' => '866', 'name' => "Waalre"],
            ['code' => '867', 'name' => "Waalwijk"],
            ['code' => '873', 'name' => "Woensdrecht"],
            ['code' => '879', 'name' => "Zundert"],
            ['code' => '880', 'name' => "Wormerland"],
            ['code' => '882', 'name' => "Landgraaf"],
            ['code' => '888', 'name' => "Beek"],
            ['code' => '889', 'name' => "Beesel"],
            ['code' => '893', 'name' => "Bergen (L.)"],
            ['code' => '899', 'name' => "Brunssum"],
            ['code' => '907', 'name' => "Gennep"],
            ['code' => '917', 'name' => "Heerlen"],
            ['code' => '928', 'name' => "Kerkrade"],
            ['code' => '935', 'name' => "Maastricht"],
            ['code' => '938', 'name' => "Meerssen"],
            ['code' => '944', 'name' => "Mook en Middelaar"],
            ['code' => '946', 'name' => "Nederweert"],
            ['code' => '957', 'name' => "Roermond"],
            ['code' => '965', 'name' => "Simpelveld"],
            ['code' => '971', 'name' => "Stein"],
            ['code' => '981', 'name' => "Vaals"],
            ['code' => '983', 'name' => "Venlo"],
            ['code' => '984', 'name' => "Venray"],
            ['code' => '986', 'name' => "Voerendaal"],
            ['code' => '988', 'name' => "Weert"],
            ['code' => '994', 'name' => "Valkenburg aan de Geul"],
            ['code' => '995', 'name' => "Lelystad"],
            ['code' => '998', 'name' => "Buitenland"],
            ['code' => '1507', 'name' => "Horst aan de Maas"],
            ['code' => '1509', 'name' => "Oude IJsselstreek"],
            ['code' => '1525', 'name' => "Teylingen"],
            ['code' => '1581', 'name' => "Utrechtse Heuvelrug"],
            ['code' => '1586', 'name' => "Oost Gelre"],
            ['code' => '1598', 'name' => "Koggenland"],
            ['code' => '1621', 'name' => "Lansingerland"],
            ['code' => '1640', 'name' => "Leudal"],
            ['code' => '1641', 'name' => "Maasgouw"],
            ['code' => '1652', 'name' => "Gemert-Bakel"],
            ['code' => '1655', 'name' => "Halderberge"],
            ['code' => '1658', 'name' => "Heeze-Leende"],
            ['code' => '1659', 'name' => "Laarbeek"],
            ['code' => '1667', 'name' => "Reusel-De Mierden"],
            ['code' => '1669', 'name' => "Roerdalen"],
            ['code' => '1674', 'name' => "Roosendaal"],
            ['code' => '1676', 'name' => "Schouwen-Duiveland"],
            ['code' => '1680', 'name' => "Aa en Hunze"],
            ['code' => '1681', 'name' => "Borger-Odoorn"],
            ['code' => '1684', 'name' => "Cuijk"],
            ['code' => '1685', 'name' => "Landerd"],
            ['code' => '1690', 'name' => "De Wolden"],
            ['code' => '1695', 'name' => "Noord-Beveland"],
            ['code' => '1696', 'name' => "Wijdemeren"],
            ['code' => '1699', 'name' => "Noordenveld"],
            ['code' => '1700', 'name' => "Twenterand"],
            ['code' => '1701', 'name' => "Westerveld"],
            ['code' => '1702', 'name' => "Sint Anthonis"],
            ['code' => '1705', 'name' => "Lingewaard"],
            ['code' => '1706', 'name' => "Cranendonck"],
            ['code' => '1708', 'name' => "Steenwijkerland"],
            ['code' => '1709', 'name' => "Moerdijk"],
            ['code' => '1711', 'name' => "Echt-Susteren"],
            ['code' => '1714', 'name' => "Sluis"],
            ['code' => '1719', 'name' => "Drimmelen"],
            ['code' => '1721', 'name' => "Bernheze"],
            ['code' => '1723', 'name' => "Alphen-Chaam"],
            ['code' => '1724', 'name' => "Bergeijk"],
            ['code' => '1728', 'name' => "Bladel"],
            ['code' => '1729', 'name' => "Gulpen-Wittem"],
            ['code' => '1730', 'name' => "Tynaarlo"],
            ['code' => '1731', 'name' => "Midden-Drenthe"],
            ['code' => '1734', 'name' => "Overbetuwe"],
            ['code' => '1735', 'name' => "Hof van Twente"],
            ['code' => '1740', 'name' => "Neder-Betuwe"],
            ['code' => '1742', 'name' => "Rijssen-Holten"],
            ['code' => '1771', 'name' => "Geldrop-Mierlo"],
            ['code' => '1773', 'name' => "Olst-Wijhe"],
            ['code' => '1774', 'name' => "Dinkelland"],
            ['code' => '1783', 'name' => "Westland"],
            ['code' => '1842', 'name' => "Midden-Delfland"],
            ['code' => '1859', 'name' => "Berkelland"],
            ['code' => '1876', 'name' => "Bronckhorst"],
            ['code' => '1883', 'name' => "Sittard-Geleen"],
            ['code' => '1884', 'name' => "Kaag en Braassem"],
            ['code' => '1891', 'name' => "Dantumadiel"],
            ['code' => '1892', 'name' => "Zuidplas"],
            ['code' => '1894', 'name' => "Peel en Maas"],
            ['code' => '1895', 'name' => "Oldambt"],
            ['code' => '1896', 'name' => "Zwartewaterland"],
            ['code' => '1900', 'name' => "Súdwest-Fryslân"],
            ['code' => '1901', 'name' => "Bodegraven-Reeuwijk"],
            ['code' => '1903', 'name' => "Eijsden-Margraten"],
            ['code' => '1904', 'name' => "Stichtse Vecht"],
            ['code' => '1911', 'name' => "Hollands Kroon"],
            ['code' => '1916', 'name' => "Leidschendam-Voorburg"],
            ['code' => '1924', 'name' => "Goeree-Overflakkee"],
            ['code' => '1926', 'name' => "Pijnacker-Nootdorp"],
            ['code' => '1930', 'name' => "Nissewaard"],
            ['code' => '1931', 'name' => "Krimpenerwaard"],
            ['code' => '1940', 'name' => "De Fryske Marren"],
            ['code' => '1942', 'name' => "Gooise Meren"],
            ['code' => '1945', 'name' => "Berg en Dal"],
            ['code' => '1948', 'name' => "Meierijstad"],
            ['code' => '1949', 'name' => "Waadhoeke"],
            ['code' => '1950', 'name' => "Westerwolde"],
            ['code' => '1952', 'name' => "Midden-Groningen"],
            ['code' => '1954', 'name' => "Beekdaelen"],
            ['code' => '1955', 'name' => "Montferland"],
            ['code' => '1959', 'name' => "Altena"],
            ['code' => '1960', 'name' => "West Betuwe"],
            ['code' => '1961', 'name' => "Vijfheerenlanden"],
            ['code' => '1963', 'name' => "Hoeksche Waard"],
            ['code' => '1966', 'name' => "Het Hogeland"],
            ['code' => '1969', 'name' => "Westerkwartier"],
            ['code' => '1970', 'name' => "Noardeast-Fryslân"],
            ['code' => '1978', 'name' => "Molenlanden"],
            ['code' => '1979', 'name' => "Eemsdelta"],
        ];
        
        foreach ($municipalities as $municipality) {
            $municipalityObject = new Municipality();

            if (empty($municipality['code'])) {
                throw new RuntimeException("code may not be empty, it's used as a variable reference in the data fixtures.");
            } else {
                $municipalityObject->setCode($municipality['code']);
            }

            if (isset($municipality['name']) && ($municipality['name'] !== '' && $municipality['name'] !== '0')) {
                $municipalityObject->setName($municipality['name']);
            }

            $validator = Validation::createValidator();
            $errors = $validator->validate($municipalityObject);
            if (count($errors) > 0) {
                $messages = [];
                foreach ($errors as $error) {
                    /** @var ConstraintViolation $error */
                    $messages[] = $error->getMessage();
                }

                throw new RuntimeException(implode(', ', $messages));
            }

            $objectManager->persist($municipalityObject);
            $this->addReference('municipality_' . $municipality['code'], $municipalityObject);
        }

        $objectManager->flush();
    }
}